# These are supported funding model platforms

#github: ['MhankBarBar', 'Krypton-Byte'] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://saweria.co/mhankbarbar', 'https://paypal.me/mhankbarbar'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
